services:
  app:
    build:
      context: .
    image: custom/mautic
    container_name: "${APP_SERVICE:-app}"
    environment:
      APP_WORKDIR: "${APP_WORKDIR:-/var/www/html}"
      MYSQL_PORT: "${DB_PORT:-3306}"
      MAUTIC_DB_HOST: "${DB_HOST:-mysql}"
      MAUTIC_DB_NAME: "${DB_NAME:-db_mautic}"
      MAUTIC_DB_USER: "${DB_USER:-mautic}"
      MAUTIC_DB_PASSWORD: "${DB_PASSWORD:-mautic}"
      MAUTIC_URL: ${APP_MAUTIC_URL}
      MAUTIC_ADMIN_USERNAME: ${APP_MAUTIC_ADMIN_USERNAME}
      MAUTIC_ADMIN_PASSWORD: ${APP_MAUTIC_ADMIN_PASSWORD}
      MAUTIC_ADMIN_EMAIL: ${APP_MAUTIC_ADMIN_EMAIL}
      MAUTIC_ADMIN_LASTNAME: ${APP_MAUTIC_ADMIN_LASTNAME}
      MAUTIC_ADMIN_FIRSTNAME: ${APP_MAUTIC_ADMIN_FIRSTNAME}
      MAUTIC_RUN_MIGRATIONS: ${APP_MAUTIC_RUN_MIGRATIONS}
      MAUTIC_INSTALL_FORCE: ${APP_MAUTIC_INSTALL_FORCE}
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ".:${APP_WORKDIR:-/var/www/html}"
    networks:
      - private
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "${DB_USER:-mautic}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-mautic}"
      MYSQL_DATABASE: "${DB_NAME:-db_mautic}"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - private

networks:
  private:
    driver: bridge

volumes:
  mysql:
    driver: local
